version: "3.8"

services:
  # Infrastructure

  eventstore:
    image: eventstore/eventstore:23.10.0-bookworm-slim
    volumes:
      - eventstore-data:/var/lib/eventstore
    ports:
      - 1113:1113
      - 2113:2113
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    networks:
      - devnet

  postgres:
    image: postgres:16.1
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=espm
    networks:
      - devnet

  rabbitmq:
    image: rabbitmq:3.12-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=changeit
      - RABBITMQ_DEFAULT_VHOST=espm
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - devnet

  ## Main Application

  app:
    depends_on:
      - rabbitmq
    build:
      context: ./src/EventSourcedPM
      dockerfile: eventsourced-pm.Dockerfile
    environment:
      - EventSourcedPM__ApiBaseUrl=http://*:43210
      - EventSourcedPM__EventStore__Endpoint__Host=eventstore
      - EventSourcedPM__EventStore__Username=admin
      - EventSourcedPM__EventStore__Password=changeit
      - EventSourcedPM__Postgres__Endpoint__Host=postgres
      - EventSourcedPM__Postgres__Username=admin
      - EventSourcedPM__Postgres__Password=changeit
      - EventSourcedPM__Postgres__Database=espm
      - EventSourcedPM__RabbitMq__Endpoint__Host=rabbitmq
      - EventSourcedPM__RabbitMq__Username=admin
      - EventSourcedPM__RabbitMq__Password=changeit
      - EventSourcedPM__RabbitMq__VHost=espm
      - EventSourcedPM__WaitForInfrastructureOnStartup=true
    ports:
      - 43210:43210
    networks:
      - devnet

volumes:
  eventstore-data:
    driver: local
  postgres-data:
    driver: local
  rabbitmq-data:
    driver: local

networks:
  devnet:
    driver: bridge
