version: "3.8"

services:
  # Infrastructure

  postgres:
    image: postgres:16.1
    command: postgres -c 'max_connections=1000'
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "changeit"
      POSTGRES_DB: "espm"
    networks:
      - devnet

  rabbitmq:
    image: rabbitmq:3.12-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=changeit
      - RABBITMQ_DEFAULT_VHOST=espm
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - devnet

  ## Main Application - 3 replicas

  app1:
    depends_on:
      - rabbitmq
    build:
      context: ./src/EventSourcedPM
      dockerfile: eventsourced-pm.Dockerfile
    environment:
      - EventSourcedPM__ApiBaseUrl=http://*:43211
      - EventSourcedPM__Postgres__Endpoint__Host=postgres
      - EventSourcedPM__Postgres__Username=admin
      - EventSourcedPM__Postgres__Password=changeit
      - EventSourcedPM__Postgres__Database=espm
      - EventSourcedPM__RabbitMq__Endpoint__Host=rabbitmq
      - EventSourcedPM__RabbitMq__Username=admin
      - EventSourcedPM__RabbitMq__Password=changeit
      - EventSourcedPM__RabbitMq__VHost=espm
      - EventSourcedPM__WaitForInfrastructureOnStartup=true
    ports:
      - "43211:43211"
    networks:
      - devnet

  app2:
    depends_on:
      - rabbitmq
    build:
      context: ./src/EventSourcedPM
      dockerfile: eventsourced-pm.Dockerfile
    environment:
      - EventSourcedPM__ApiBaseUrl=http://*:43212
      - EventSourcedPM__Postgres__Endpoint__Host=postgres
      - EventSourcedPM__Postgres__Username=admin
      - EventSourcedPM__Postgres__Password=changeit
      - EventSourcedPM__Postgres__Database=espm
      - EventSourcedPM__RabbitMq__Endpoint__Host=rabbitmq
      - EventSourcedPM__RabbitMq__Username=admin
      - EventSourcedPM__RabbitMq__Password=changeit
      - EventSourcedPM__RabbitMq__VHost=espm
      - EventSourcedPM__WaitForInfrastructureOnStartup=true
    ports:
      - "43212:43212"
    networks:
      - devnet

  app3:
    depends_on:
      - rabbitmq
    build:
      context: ./src/EventSourcedPM
      dockerfile: eventsourced-pm.Dockerfile
    environment:
      - EventSourcedPM__ApiBaseUrl=http://*:43213
      - EventSourcedPM__Postgres__Endpoint__Host=postgres
      - EventSourcedPM__Postgres__Username=admin
      - EventSourcedPM__Postgres__Password=changeit
      - EventSourcedPM__Postgres__Database=espm
      - EventSourcedPM__RabbitMq__Endpoint__Host=rabbitmq
      - EventSourcedPM__RabbitMq__Username=admin
      - EventSourcedPM__RabbitMq__Password=changeit
      - EventSourcedPM__RabbitMq__VHost=espm
      - EventSourcedPM__WaitForInfrastructureOnStartup=true
    ports:
      - "43213:43213"
    networks:
      - devnet

## NGINX load balancer
  proxy:
    depends_on:
      - app1
      - app2
      - app3
    build:
      context: ./proxy
      dockerfile: proxy.Dockerfile
    ports:
      - "43210:43210"
    networks:
      - devnet

volumes:
  postgres-data:
    driver: local
  eventstore-data:
    driver: local
  eventstore-logs:
    driver: local
  rabbitmq-data:
    driver: local

networks:
  devnet:
    driver: bridge
