services:
  eventstore:
    image: eventstore/eventstore:24.10.7-alpha-arm64v8
    volumes:
      - eventstore-data:/var/lib/eventstore
    ports:
      - 1113:1113
      - 2113:2113
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    networks:
      - devnet

  postgres:
    image: postgres:17.6
    command: postgres -c 'max_connections=1000'
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=espm
    networks:
      - devnet

  rabbitmq:
    image: rabbitmq:4.1-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=changeit
      - RABBITMQ_DEFAULT_VHOST=espm
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - devnet
