version: "3.8"

services:
  eventstore:
    image: eventstore/eventstore:23.10.0-bookworm-slim
    volumes:
      - eventstore-data:/var/lib/eventstore
    ports:
      - 1113:1113
      - 2113:2113
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    networks:
      - devnet

  postgres:
    image: postgres:16.1
    command: postgres -c 'max_connections=1000'
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=espm
    networks:
      - devnet

  rabbitmq:
    image: rabbitmq:3.12-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=changeit
      - RABBITMQ_DEFAULT_VHOST=espm
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - devnet

volumes:
  eventstore-data:
    driver: local
  postgres-data:
    driver: local
  rabbitmq-data:
    driver: local

networks:
  devnet:
    driver: bridge
